version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=medi_note_user
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=medi_note_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: {}

